//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoppingCart.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class logindetail
    {

       
        public int login_id { get; set; }

        [Display(Name ="First Name")]
        [Required(ErrorMessage ="This field is required")]
        public string First_name { get; set; }

        [Display(Name = "Middle Name")]
        public string Middle_name { get; set; }

        [Display(Name = "Last Name")]
        [Required(ErrorMessage = "This field is required")]
        public string Last_name { get; set; }

        [Display(Name = "Gender")]
        public string gender { get; set; }
        public Nullable<System.DateTime> dob { get; set; }

        [Display(Name = "Email")]
        [Required(ErrorMessage = "This field is required")]
        public string email { get; set; }

        [Display(Name = "Password")]
        [Required(ErrorMessage = "This field is required")]
        public string password { get; set; }

        [Display(Name = "Confirm Password")]
        [Required(ErrorMessage = "This field is required")]
        [Compare("Password", ErrorMessage = "Confirm password doesn't match, Type again !")]
        public string confirm_password { get; set; }
        public string roles { get; set; }
    }
}
