//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoppingCart.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class productdetail
    {

        [Display(Name ="Product Id")]
        public int product_id { get; set; }

        [Display(Name ="Product Name")]
        public string product_name { get; set; }

        [Display(Name = "Category Id")]
        public Nullable<int> category_id { get; set; }

        [Display(Name = "Brand Id")]
        public Nullable<int> brand_id { get; set; }

        [Display(Name = "Description")]
        public string description { get; set; }

        [Display(Name = "Price")]
        public decimal price { get; set; }

        [Display(Name = "Current Stock")]
        public Nullable<int> current_stock { get; set; }

        [Display(Name = "Created By")]
        public string created_by { get; set; }

        [Display(Name = "Created Date")]
        public Nullable<System.DateTime> created_date { get; set; }

        [Display(Name = "Updated By")]
        public string updated_by { get; set; }

        [Display(Name = "Updated Date")]
        public Nullable<System.DateTime> updated_date { get; set; }

        [Display(Name = "Is active")]
        public Nullable<bool> is_active { get; set; }

       
        public virtual brand brand { get; set; }

       
        public virtual category category { get; set; }
    }
}
